name: "service-subsystem"
services:
  postgres:
    image: postgres:15-alpine
    container_name: service-postgres
    environment:
      POSTGRES_DB: alina_diplom
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Nosorog228GG
    ports:
      - "6789:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    cpus: 0.6

  backend:
    build: ./spring_backend
    container_name: service-backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - app-network
    cpus: 0.6

  frontend:
    build: ./react_frontend
    container_name: service-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network
    cpus: 0.6

volumes:
  postgres_data:


networks:
  app-network:
    driver: bridge
